# **************************************************************************** #
#
# docker-compose.yml
#
# user: mlanca-c
# URL: https://github.com/mlanca-c/inception
# description: this file defines and runs multiple container applications
# **************************************************************************** #

# docker-compose version set to the latest, default being 1
version: '3.8'

# List of services (containers)
services:
  # nginx container
  nginx:
    # name of the container
    container_name: nginx
    # name of the image (syntax: name[:tag])
    image: nginx:prod
    # build section. This regards the image of the container
    build:
      # location of the Dockerfile
      context: ./requirements/nginx/.
    # port to be accessed outside of docker network (syntax: HOST:CONTAINER)
    ports:
      - "443:443"
    # restart is set to on-failure, this way the container only restarts if it
    # fails
    # restart: on-failure
    # app network
    networks:
      - inception-network
    # this docker container will depend on other containers
    depends_on:
      - wordpress
      - mariadb
    # mounting local filesystems inside container
    volumes:
      - wordpress-volume:/var/www/html

volumes:

  wordpress-volume:
    name: wordpress-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mlancac/data/wordpress-volume

# app network
networks:
  inception-network:
    name: inception-network
